const DIRS={right:{dr:0,dc:1,angle:0},down:{dr:1,dc:0,angle:90},left:{dr:0,dc:-1,angle:180},up:{dr:-1,dc:0,angle:-90}};
const board=document.getElementById('board'),message=document.getElementById('message'),levelNumber=document.getElementById('levelNumber'),leftCount=document.getElementById('leftCount'),restartButton=document.getElementById('restartButton'),newButton=document.getElementById('newButton'),nextButton=document.getElementById('nextButton');
let level=0,size=9,arrows=[],currentSeed=1931,solved=false,animating=false;
function rng(seed){let x=seed>>>0||1;return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967296}}
function key(r,c){return`${r},${c}`}
function adjacent(a,b){return Math.abs(a.r-b.r)+Math.abs(a.c-b.c)===1}
function difficultyForLevel(index){const n=Math.min(11,9+Math.floor(index/2)),minLen=Math.min(10,6+Math.floor(index/3)),maxLen=Math.min(18,12+Math.floor(index/2));return{n,minLen,maxLen}}
function buildSerpentineCells(n){const cells=[];for(let r=0;r<n;r++){if(r%2===0){for(let c=0;c<n;c++)cells.push({r,c})}else{for(let c=n-1;c>=0;c--)cells.push({r,c})}}return cells}
// Hamiltonian pathを壊さない2-opt反転を何度もかけて、規則的な蛇行を迷路っぽく崩す。
function scrambleHamiltonianPath(cells,random,passes){const path=cells.map(c=>({...c}));for(let p=0;p<passes;p++){const i=Math.floor(random()*(path.length-4));const j=i+2+Math.floor(random()*Math.max(1,path.length-i-3));if(j>=path.length-1)continue;if(adjacent(path[i],path[j])&&adjacent(path[i+1],path[j+1])){const rev=path.slice(i+1,j+1).reverse();path.splice(i+1,rev.length,...rev)}}return path}
function splitIntoLongArrows(cells,random,minLen,maxLen){const chunks=[];let i=0;while(i<cells.length){const remaining=cells.length-i;let len;if(remaining<=maxLen)len=remaining;else{len=minLen+Math.floor(random()*(maxLen-minLen+1));const after=remaining-len;if(after>0&&after<minLen)len-=(minLen-after)}len=Math.max(3,Math.min(len,remaining));chunks.push(cells.slice(i,i+len));i+=len}if(chunks.length>1&&chunks[chunks.length-1].length<4)chunks[chunks.length-2].push(...chunks.pop());return chunks}
function directionFromLastStep(cells){const a=cells[cells.length-2],b=cells[cells.length-1],dr=b.r-a.r,dc=b.c-a.c;if(dc===1)return'right';if(dc===-1)return'left';if(dr===1)return'down';return'up'}
function buildCandidates(seed,diff){const random=rng(seed);for(let attempt=0;attempt<28;attempt++){let allCells=buildSerpentineCells(diff.n);allCells=scrambleHamiltonianPath(allCells,random,diff.n*diff.n*(36+attempt));const chunks=splitIntoLongArrows(allCells,random,diff.minLen,diff.maxLen),candidate=chunks.map((cells,id)=>({id,cells,dir:directionFromLastStep(cells),removed:false}));if(isSolvable(candidate,diff.n))return candidate}const fallback=splitIntoLongArrows(buildSerpentineCells(diff.n),random,diff.minLen,diff.maxLen);return fallback.map((cells,id)=>({id,cells,dir:directionFromLastStep(cells),removed:false}))}
function generatePuzzle(seed){const diff=difficultyForLevel(level);size=diff.n;board.style.setProperty('--n',size);arrows=buildCandidates(seed,diff);solved=false;animating=false;nextButton.disabled=true;render()}
function occupancyFor(list,activeIds){const map=new Map();list.forEach(a=>{if(!activeIds.has(a.id))return;a.cells.forEach((c,idx)=>map.set(key(c.r,c),{arrowId:a.id,index:idx}))});return map}
function blockingInfoFor(list,arrow,activeIds,n){const headIndex=arrow.cells.length-1,head=arrow.cells[headIndex],d=DIRS[arrow.dir],occupied=occupancyFor(list,activeIds);let r=head.r+d.dr,c=head.c+d.dc,steps=1;while(r>=0&&r<n&&c>=0&&c<n){const hit=occupied.get(key(r,c));if(hit&&(hit.arrowId!==arrow.id||hit.index<headIndex-1))return{blocked:true,steps,row:r,col:c,hitArrowId:hit.arrowId};r+=d.dr;c+=d.dc;steps++}return{blocked:false,steps}}
function isSolvable(list,n){const active=new Set(list.map(a=>a.id));let changed=true;while(active.size&&changed){changed=false;for(const a of list){if(!active.has(a.id))continue;if(!blockingInfoFor(list,a,active,n).blocked){active.delete(a.id);changed=true}}}return active.size===0}
function blockingInfo(arrow){const active=new Set(arrows.filter(a=>!a.removed).map(a=>a.id));return blockingInfoFor(arrows,arrow,active,size)}
function cellCenter(cell){const step=1000/size;return{x:(cell.c+.5)*step,y:(cell.r+.5)*step}}
function pathDataForCells(cells,extend=false,dirName=null,extendDistance=1500){const points=cells.map(cellCenter);if(extend&&dirName){const d=DIRS[dirName],head=points[points.length-1];points.push({x:head.x+d.dc*extendDistance,y:head.y+d.dr*extendDistance})}return points.map((p,i)=>`${i===0?'M':'L'} ${p.x} ${p.y}`).join(' ')}
function createArrowGroup(arrow){const ns='http://www.w3.org/2000/svg',group=document.createElementNS(ns,'g');group.classList.add('snake-arrow');group.dataset.id=arrow.id;const halo=document.createElementNS(ns,'path');halo.classList.add('snake-halo');halo.setAttribute('d',pathDataForCells(arrow.cells));const path=document.createElementNS(ns,'path');path.classList.add('snake-line');path.setAttribute('d',pathDataForCells(arrow.cells));const hit=document.createElementNS(ns,'path');hit.classList.add('snake-hit');hit.setAttribute('d',pathDataForCells(arrow.cells));const headHalo=document.createElementNS(ns,'polygon');headHalo.classList.add('snake-head-halo');headHalo.setAttribute('points','-38,-34 38,0 -38,34');const head=document.createElementNS(ns,'polygon');head.classList.add('snake-head');head.setAttribute('points','-32,-28 36,0 -32,28');const end=cellCenter(arrow.cells[arrow.cells.length-1]),transform=`translate(${end.x} ${end.y}) rotate(${DIRS[arrow.dir].angle})`;headHalo.setAttribute('transform',transform);head.setAttribute('transform',transform);hit.addEventListener('click',()=>tapArrow(arrow,group));head.addEventListener('click',()=>tapArrow(arrow,group));headHalo.addEventListener('click',()=>tapArrow(arrow,group));group.append(halo,path,hit,headHalo,head);return group}
function render(){board.innerHTML='';levelNumber.textContent=level+1;const active=arrows.filter(a=>!a.removed);leftCount.textContent=active.length;message.textContent='先が空いている長い矢印をタップ！';const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.classList.add('arrow-canvas');svg.setAttribute('viewBox','0 0 1000 1000');svg.setAttribute('aria-label','蛇行する矢印脱出パズル');active.forEach(a=>svg.appendChild(createArrowGroup(a)));board.appendChild(svg)}
function tapArrow(arrow,group){if(solved||animating||arrow.removed||group.classList.contains('escaping'))return;const info=blockingInfo(arrow);animating=true;group.classList.add('escaping');if(info.blocked){message.textContent='スルスル…';blockedLikeTrain(group,arrow,info);return}arrow.removed=true;message.textContent='スルルルッ… ➜';leftCount.textContent=arrows.filter(a=>!a.removed).length;escapeLikeTrain(group,arrow)}
function prepareRail(group,arrow,extendDistance){const ns='http://www.w3.org/2000/svg',originalPath=group.querySelector('.snake-line'),halo=group.querySelector('.snake-halo'),originalHead=group.querySelector('.snake-head'),headHalo=group.querySelector('.snake-head-halo'),originalD=originalPath.getAttribute('d'),rail=document.createElementNS(ns,'path');rail.classList.add('escape-rail');rail.setAttribute('d',pathDataForCells(arrow.cells,true,arrow.dir,extendDistance));rail.setAttribute('fill','none');rail.setAttribute('stroke','none');group.appendChild(rail);const bodyLength=originalPath.getTotalLength(),railLength=rail.getTotalLength();[originalPath,halo].forEach(el=>{el.setAttribute('d',rail.getAttribute('d'));el.style.strokeDasharray=`${bodyLength} ${railLength+bodyLength}`;el.style.strokeDashoffset='0'});const hit=group.querySelector('.snake-hit');if(hit)hit.remove();return{rail,originalPath,halo,originalHead,headHalo,originalD,bodyLength,railLength}}
function setTrainPosition(parts,moved){const{rail,originalPath,halo,originalHead,headHalo,bodyLength,railLength}=parts;[originalPath,halo].forEach(el=>el.style.strokeDashoffset=`${-moved}`);const front=Math.min(railLength,bodyLength+moved),p=rail.getPointAtLength(front),p2=rail.getPointAtLength(Math.max(0,front-5)),angle=Math.atan2(p.y-p2.y,p.x-p2.x)*180/Math.PI,transform=`translate(${p.x} ${p.y}) rotate(${angle})`;originalHead.setAttribute('transform',transform);headHalo.setAttribute('transform',transform)}
function escapeLikeTrain(group,arrow){const parts=prepareRail(group,arrow,1500),travel=parts.railLength-parts.bodyLength,duration=Math.min(2200,950+arrow.cells.length*72),start=performance.now();function frame(now){const raw=Math.min(1,(now-start)/duration),eased=raw<.12?(raw/.12)*.035:.035+.965*(1-Math.pow(1-(raw-.12)/.88,3));setTrainPosition(parts,travel*eased);if(raw<1)return requestAnimationFrame(frame);group.remove();animating=false;if(arrows.every(a=>a.removed))finishLevel();else message.textContent='いい感じ！ 次に抜ける矢印はどれ？'}requestAnimationFrame(frame)}
function blockedLikeTrain(group,arrow,info){const step=1000/size,approach=Math.max(step*.12,(info.steps-.72)*step),parts=prepareRail(group,arrow,approach),travel=parts.railLength-parts.bodyLength,forwardDuration=Math.min(1100,420+info.steps*95),backDuration=Math.min(900,360+info.steps*70),start=performance.now();function forward(now){const raw=Math.min(1,(now-start)/forwardDuration),eased=1-Math.pow(1-raw,2.1);setTrainPosition(parts,travel*eased);if(raw<1)return requestAnimationFrame(forward);impact()}function impact(){message.textContent='ゴツン！ 💥';group.classList.add('impact');if(navigator.vibrate)navigator.vibrate(35);setTimeout(()=>{group.classList.remove('impact');const backStart=performance.now();function back(now){const raw=Math.min(1,(now-backStart)/backDuration),eased=1-Math.pow(1-raw,2.15);setTrainPosition(parts,travel*(1-eased));if(raw<1)return requestAnimationFrame(back);restore()}requestAnimationFrame(back)},190)}function restore(){[parts.originalPath,parts.halo].forEach(el=>{el.setAttribute('d',parts.originalD);el.style.strokeDasharray='';el.style.strokeDashoffset=''});parts.rail.remove();const end=cellCenter(arrow.cells[arrow.cells.length-1]),transform=`translate(${end.x} ${end.y}) rotate(${DIRS[arrow.dir].angle})`;parts.originalHead.setAttribute('transform',transform);parts.headHalo.setAttribute('transform',transform);group.classList.remove('escaping');animating=false;message.textContent='戻った！ 別の矢印からほどいてみよう'}requestAnimationFrame(forward)}
function finishLevel(){solved=true;message.textContent='🎉 CLEAR! 全部の矢印が脱出した！';nextButton.disabled=false;celebrate()}
function celebrate(){const layer=document.getElementById('celebration');layer.innerHTML='';const marks=['➜','↑','←','↓','✨'];for(let i=0;i<44;i++){const s=document.createElement('span');s.className='confetti';s.textContent=marks[Math.floor(Math.random()*marks.length)];s.style.left=`${Math.random()*100}%`;s.style.setProperty('--drift',`${(Math.random()-.5)*240}px`);s.style.animationDelay=`${Math.random()*.38}s`;layer.appendChild(s)}setTimeout(()=>layer.innerHTML='',2400)}
function restart(){if(animating)return;generatePuzzle(currentSeed)}
function newPuzzle(){if(animating)return;currentSeed=(Date.now()^Math.floor(Math.random()*0x7fffffff))>>>0;generatePuzzle(currentSeed)}
function nextLevel(){if(animating)return;level+=1;currentSeed=(1931+level*7919)>>>0;generatePuzzle(currentSeed)}
restartButton.addEventListener('click',restart);newButton.addEventListener('click',newPuzzle);nextButton.addEventListener('click',nextLevel);generatePuzzle(currentSeed);
