const DIRS={right:{dr:0,dc:1,angle:0},down:{dr:1,dc:0,angle:90},left:{dr:0,dc:-1,angle:180},up:{dr:-1,dc:0,angle:-90}};
const board=document.getElementById('board'),message=document.getElementById('message'),levelNumber=document.getElementById('levelNumber'),leftCount=document.getElementById('leftCount'),restartButton=document.getElementById('restartButton'),newButton=document.getElementById('newButton'),nextButton=document.getElementById('nextButton');
let level=0,size=9,arrows=[],currentSeed=1931,solved=false,animating=false;
function rng(seed){let x=seed>>>0||1;return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967296}}
function key(r,c){return`${r},${c}`}
function difficultyForLevel(index){const n=Math.min(12,9+Math.floor(index/2)),minLen=Math.min(9,6+Math.floor(index/3)),maxLen=Math.min(15,10+Math.floor(index/2));return{n,minLen,maxLen}}
function buildSerpentineCells(n){const cells=[];for(let r=0;r<n;r++){if(r%2===0){for(let c=0;c<n;c++)cells.push({r,c})}else{for(let c=n-1;c>=0;c--)cells.push({r,c})}}return cells}
function splitIntoLongArrows(cells,random,minLen,maxLen){const chunks=[];let i=0;while(i<cells.length){const remaining=cells.length-i;let len;if(remaining<=maxLen)len=remaining;else{len=minLen+Math.floor(random()*(maxLen-minLen+1));const after=remaining-len;if(after>0&&after<minLen)len-=(minLen-after)}len=Math.max(2,Math.min(len,remaining));chunks.push(cells.slice(i,i+len));i+=len}if(chunks.length>1&&chunks[chunks.length-1].length<4)chunks[chunks.length-2].push(...chunks.pop());return chunks}
function directionFromLastStep(cells){const a=cells[cells.length-2],b=cells[cells.length-1],dr=b.r-a.r,dc=b.c-a.c;if(dc===1)return'right';if(dc===-1)return'left';if(dr===1)return'down';return'up'}
function generatePuzzle(seed){const random=rng(seed),diff=difficultyForLevel(level);size=diff.n;board.style.setProperty('--n',size);const allCells=buildSerpentineCells(size),chunks=splitIntoLongArrows(allCells,random,diff.minLen,diff.maxLen);arrows=chunks.map((cells,id)=>({id,cells,dir:directionFromLastStep(cells),removed:false}));solved=false;animating=false;nextButton.disabled=true;render()}
function activeOccupancy(exceptId=null){const occupied=new Set();arrows.forEach(a=>{if(a.removed||a.id===exceptId)return;a.cells.forEach(c=>occupied.add(key(c.r,c)))});return occupied}
function blockingInfo(arrow){const head=arrow.cells[arrow.cells.length-1],d=DIRS[arrow.dir],occupied=activeOccupancy(arrow.id);let r=head.r+d.dr,c=head.c+d.dc,steps=1;while(r>=0&&r<size&&c>=0&&c<size){if(occupied.has(key(r,c)))return{blocked:true,steps,row:r,col:c};r+=d.dr;c+=d.dc;steps++}return{blocked:false,steps}}
function canEscape(arrow){return!blockingInfo(arrow).blocked}
function cellCenter(cell){const step=1000/size;return{x:(cell.c+.5)*step,y:(cell.r+.5)*step}}
function pathDataForCells(cells,extend=false,dirName=null,extendDistance=1500){const points=cells.map(cellCenter);if(extend&&dirName){const d=DIRS[dirName],head=points[points.length-1];points.push({x:head.x+d.dc*extendDistance,y:head.y+d.dr*extendDistance})}return points.map((p,i)=>`${i===0?'M':'L'} ${p.x} ${p.y}`).join(' ')}
function createArrowGroup(arrow){const ns='http://www.w3.org/2000/svg',group=document.createElementNS(ns,'g');group.classList.add('snake-arrow');group.dataset.id=arrow.id;const path=document.createElementNS(ns,'path');path.classList.add('snake-line');path.setAttribute('d',pathDataForCells(arrow.cells));const hit=document.createElementNS(ns,'path');hit.classList.add('snake-hit');hit.setAttribute('d',pathDataForCells(arrow.cells));const head=document.createElementNS(ns,'polygon');head.classList.add('snake-head');head.setAttribute('points','-25,-20 22,0 -25,20');const end=cellCenter(arrow.cells[arrow.cells.length-1]);head.setAttribute('transform',`translate(${end.x} ${end.y}) rotate(${DIRS[arrow.dir].angle})`);hit.addEventListener('click',()=>tapArrow(arrow,group));head.addEventListener('click',()=>tapArrow(arrow,group));group.append(path,hit,head);return group}
function render(){board.innerHTML='';levelNumber.textContent=level+1;const active=arrows.filter(a=>!a.removed);leftCount.textContent=active.length;message.textContent='先が空いている長い矢印をタップ！';const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.classList.add('arrow-canvas');svg.setAttribute('viewBox','0 0 1000 1000');svg.setAttribute('aria-label','蛇行する矢印脱出パズル');active.forEach(a=>svg.appendChild(createArrowGroup(a)));board.appendChild(svg)}
function tapArrow(arrow,group){if(solved||animating||arrow.removed||group.classList.contains('escaping'))return;const info=blockingInfo(arrow);animating=true;group.classList.add('escaping');if(info.blocked){message.textContent='スルスル… ゴツン！';blockedLikeTrain(group,arrow,info);return}arrow.removed=true;message.textContent='スルルルッ… ➜';leftCount.textContent=arrows.filter(a=>!a.removed).length;escapeLikeTrain(group,arrow)}
function prepareRail(group,arrow,extendDistance){const ns='http://www.w3.org/2000/svg',originalPath=group.querySelector('.snake-line'),originalHead=group.querySelector('.snake-head'),originalD=originalPath.getAttribute('d'),rail=document.createElementNS(ns,'path');rail.classList.add('escape-rail');rail.setAttribute('d',pathDataForCells(arrow.cells,true,arrow.dir,extendDistance));rail.setAttribute('fill','none');rail.setAttribute('stroke','none');group.appendChild(rail);const bodyLength=originalPath.getTotalLength(),railLength=rail.getTotalLength();originalPath.setAttribute('d',rail.getAttribute('d'));originalPath.style.strokeDasharray=`${bodyLength} ${railLength+bodyLength}`;originalPath.style.strokeDashoffset='0';const hit=group.querySelector('.snake-hit');if(hit)hit.remove();return{rail,originalPath,originalHead,originalD,bodyLength,railLength}}
function setTrainPosition(parts,moved){const{rail,originalPath,originalHead,bodyLength,railLength}=parts;originalPath.style.strokeDashoffset=`${-moved}`;const front=Math.min(railLength,bodyLength+moved),p=rail.getPointAtLength(front),p2=rail.getPointAtLength(Math.max(0,front-3)),angle=Math.atan2(p.y-p2.y,p.x-p2.x)*180/Math.PI;originalHead.setAttribute('transform',`translate(${p.x} ${p.y}) rotate(${angle})`)}
function escapeLikeTrain(group,arrow){const parts=prepareRail(group,arrow,1500),travel=parts.railLength-parts.bodyLength,duration=Math.min(1900,800+arrow.cells.length*70),start=performance.now();function frame(now){const raw=Math.min(1,(now-start)/duration),eased=raw<.12?(raw/.12)*.035:.035+.965*(1-Math.pow(1-(raw-.12)/.88,3));setTrainPosition(parts,travel*eased);if(raw<1)return requestAnimationFrame(frame);group.remove();animating=false;if(arrows.every(a=>a.removed))finishLevel();else message.textContent='いい感じ！ 次に抜ける矢印はどれ？'}requestAnimationFrame(frame)}
function blockedLikeTrain(group,arrow,info){const step=1000/size;
  // 障害物の中心より少し手前で頭を止める。矢印の先端ぶんも余白を取る。
  const approach=Math.max(step*.28,(info.steps-.52)*step),parts=prepareRail(group,arrow,approach),travel=parts.railLength-parts.bodyLength;
  const forwardDuration=Math.min(950,380+info.steps*90),backDuration=Math.min(800,340+info.steps*65),start=performance.now();
  function forward(now){const raw=Math.min(1,(now-start)/forwardDuration),eased=1-Math.pow(1-raw,2.2);setTrainPosition(parts,travel*eased);if(raw<1)return requestAnimationFrame(forward);impact()}
  function impact(){message.textContent='ゴツン！ 💥';parts.originalPath.style.stroke='#ef4444';parts.originalHead.style.fill='#ef4444';const d=DIRS[arrow.dir],base=parts.originalHead.getAttribute('transform');parts.originalHead.animate([{transform:`translate(${d.dc*0}px,${d.dr*0}px)`},{transform:`translate(${-d.dc*9}px,${-d.dr*9}px)`},{transform:'translate(0,0)'}],{duration:180,easing:'ease-out'});setTimeout(()=>{parts.originalPath.style.stroke='';parts.originalHead.style.fill='';const backStart=performance.now();function back(now){const raw=Math.min(1,(now-backStart)/backDuration),eased=raw<.15?raw*.45:1-Math.pow(1-raw,2.2);setTrainPosition(parts,travel*(1-eased));if(raw<1)return requestAnimationFrame(back);restore()}requestAnimationFrame(back)},170)}
  function restore(){parts.originalPath.setAttribute('d',parts.originalD);parts.originalPath.style.strokeDasharray='';parts.originalPath.style.strokeDashoffset='';parts.rail.remove();const end=cellCenter(arrow.cells[arrow.cells.length-1]);parts.originalHead.setAttribute('transform',`translate(${end.x} ${end.y}) rotate(${DIRS[arrow.dir].angle})`);group.classList.remove('escaping');animating=false;message.textContent='戻った！ 別の矢印からほどいてみよう'}
  requestAnimationFrame(forward)}
function finishLevel(){solved=true;message.textContent='🎉 CLEAR! 全部の矢印が脱出した！';nextButton.disabled=false;celebrate()}
function celebrate(){const layer=document.getElementById('celebration');layer.innerHTML='';const marks=['➜','↑','←','↓','✨'];for(let i=0;i<44;i++){const s=document.createElement('span');s.className='confetti';s.textContent=marks[Math.floor(Math.random()*marks.length)];s.style.left=`${Math.random()*100}%`;s.style.setProperty('--drift',`${(Math.random()-.5)*240}px`);s.style.animationDelay=`${Math.random()*.38}s`;layer.appendChild(s)}setTimeout(()=>layer.innerHTML='',2400)}
function restart(){if(animating)return;generatePuzzle(currentSeed)}
function newPuzzle(){if(animating)return;currentSeed=(Date.now()^Math.floor(Math.random()*0x7fffffff))>>>0;generatePuzzle(currentSeed)}
function nextLevel(){if(animating)return;level+=1;currentSeed=(1931+level*7919)>>>0;generatePuzzle(currentSeed)}
restartButton.addEventListener('click',restart);newButton.addEventListener('click',newPuzzle);nextButton.addEventListener('click',nextLevel);generatePuzzle(currentSeed);
